/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package mechanicalmanagement;

import tableModel.MecanicoTableModel;
import dao.MecanicoDAO;
import entidades.Mecanico;
import java.util.List;
import javax.swing.JOptionPane;

public class ConsultaMecanico extends javax.swing.JFrame {

    /**
     * Creates new form ConsultaVeiculo
     */
    private CadastroDeMecanicos cadastroDeMecanicos;
    private CadastroDeOrdemServico cadastroDeOrdemServico;

    public ConsultaMecanico() {
        initComponents();
    }

    public ConsultaMecanico(CadastroDeMecanicos cadastroDeMecanicos) {
        this.cadastroDeMecanicos = cadastroDeMecanicos;
        initComponents();
    }

    public ConsultaMecanico(CadastroDeOrdemServico cadastroDeOrdemServico) {
        this.cadastroDeOrdemServico = cadastroDeOrdemServico;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jBGconsulta = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jTFbusca = new javax.swing.JTextField();
        jRBnome = new javax.swing.JRadioButton();
        jRBEspecialidade = new javax.swing.JRadioButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jRBtodos = new javax.swing.JRadioButton();
        jBselecionar = new javax.swing.JButton();
        jBprocurar = new javax.swing.JButton();
        jRBcpf = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new MecanicoTableModel(MecanicoDAO.obterTodos()));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 370, 231));
        getContentPane().add(jTFbusca, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 280, -1));

        jRBnome.setBackground(new java.awt.Color(255, 255, 255));
        jBGconsulta.add(jRBnome);
        jRBnome.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jRBnome.setText("Nome");
        getContentPane().add(jRBnome, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        jRBEspecialidade.setBackground(new java.awt.Color(255, 255, 255));
        jBGconsulta.add(jRBEspecialidade);
        jRBEspecialidade.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jRBEspecialidade.setText("especialidade");
        jRBEspecialidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRBEspecialidadeActionPerformed(evt);
            }
        });
        getContentPane().add(jRBEspecialidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, 100, -1));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jLabel1.setText("Selecione a linha desejada e clique em \"selecionar\".");

        jRBtodos.setBackground(new java.awt.Color(255, 255, 255));
        jBGconsulta.add(jRBtodos);
        jRBtodos.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jRBtodos.setSelected(true);
        jRBtodos.setText("Todos");
        jRBtodos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRBtodosActionPerformed(evt);
            }
        });

        jBselecionar.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jBselecionar.setText("Selecionar");
        jBselecionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBselecionarActionPerformed(evt);
            }
        });

        jBprocurar.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jBprocurar.setText("Procurar");
        jBprocurar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBprocurarActionPerformed(evt);
            }
        });

        jRBcpf.setBackground(new java.awt.Color(255, 255, 255));
        jBGconsulta.add(jRBcpf);
        jRBcpf.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jRBcpf.setText("CPF");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(jRBcpf)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jRBtodos)
                .addGap(135, 135, 135))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                        .addComponent(jBprocurar, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jBselecionar)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRBtodos)
                    .addComponent(jRBcpf))
                .addGap(4, 4, 4)
                .addComponent(jBprocurar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 249, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jBselecionar))
                .addGap(17, 17, 17))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 410, 360));

        setSize(new java.awt.Dimension(405, 389));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jBselecionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBselecionarActionPerformed
        if (jTable1.getSelectedRow() > -1) {
            String nome = jTable1.getValueAt(jTable1.getSelectedRow(), 0).toString();
            Mecanico mecanico = MecanicoDAO.obterPorNome(nome).get(0);
            if (cadastroDeMecanicos != null) {
                cadastroDeMecanicos.consultaMecanico(mecanico);
            }
            if (cadastroDeOrdemServico != null) {
                cadastroDeOrdemServico.consultaMecanico(mecanico);
            }
            dispose();
        } else {
            JOptionPane.showMessageDialog(rootPane, "Favor selecionar uma linha");
        }
    }//GEN-LAST:event_jBselecionarActionPerformed

    private void jBprocurarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBprocurarActionPerformed
        if (jRBcpf.isSelected()) {
            List<Mecanico> mecanicos = MecanicoDAO.obterPorCpf(jTFbusca.getText());
            jTable1.setModel(new MecanicoTableModel(mecanicos));
        }

        if (jRBnome.isSelected()) {
            List<Mecanico> mecanicos = MecanicoDAO.obterPorNome(jTFbusca.getText());
            jTable1.setModel(new MecanicoTableModel(mecanicos));
        }

        if (jRBEspecialidade.isSelected()) {
            List<Mecanico> mecanicos = MecanicoDAO.obterPorEspecialidade(jTFbusca.getText());
            jTable1.setModel(new MecanicoTableModel(mecanicos));
        }

        if (jRBtodos.isSelected()) {
            List<Mecanico> mecanicos = MecanicoDAO.obterTodos();
            jTable1.setModel(new MecanicoTableModel(mecanicos));
        }
    }//GEN-LAST:event_jBprocurarActionPerformed

    private void jRBtodosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRBtodosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRBtodosActionPerformed

    private void jRBEspecialidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRBEspecialidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRBEspecialidadeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConsultaMecanico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConsultaMecanico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConsultaMecanico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConsultaMecanico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new ConsultaMecanico().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup jBGconsulta;
    private javax.swing.JButton jBprocurar;
    private javax.swing.JButton jBselecionar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRBEspecialidade;
    private javax.swing.JRadioButton jRBcpf;
    private javax.swing.JRadioButton jRBnome;
    private javax.swing.JRadioButton jRBtodos;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTFbusca;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
