/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package mechanicalmanagement;

import tableModel.ClienteTableModel;
import dao.ClienteDAO;
import entidades.Cliente;
import java.util.List;
import javax.swing.JOptionPane;

public class ConsultaCliente extends javax.swing.JFrame {

    /**
     * Creates new form ConsultaVeiculo
     */
    private CadastroDeClientes cadastroDeClientes;

    public ConsultaCliente() {
        initComponents();
        jTable1.setModel(new ClienteTableModel(ClienteDAO.obterTodos()));
    }

    public ConsultaCliente(CadastroDeClientes cadastroDeClientes) {
        this.cadastroDeClientes = cadastroDeClientes;
        initComponents();
        jTable1.setModel(new ClienteTableModel(ClienteDAO.obterTodos()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jBGconsulta = new javax.swing.ButtonGroup();
        jBselecionar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jTFbusca = new javax.swing.JTextField();
        jBprocurar = new javax.swing.JButton();
        jRBnome = new javax.swing.JRadioButton();
        jRBcpf = new javax.swing.JRadioButton();
        jRBrg = new javax.swing.JRadioButton();
        jRBtodos = new javax.swing.JRadioButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jBselecionar.setText("Selecionar");
        jBselecionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBselecionarActionPerformed(evt);
            }
        });
        getContentPane().add(jBselecionar, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 320, -1, -1));

        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 380, 231));
        getContentPane().add(jTFbusca, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 290, -1));

        jBprocurar.setText("Procurar");
        jBprocurar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBprocurarActionPerformed(evt);
            }
        });
        getContentPane().add(jBprocurar, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 50, 80, -1));

        jRBnome.setBackground(new java.awt.Color(255, 255, 255));
        jBGconsulta.add(jRBnome);
        jRBnome.setText("Nome");
        getContentPane().add(jRBnome, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        jRBcpf.setBackground(new java.awt.Color(255, 255, 255));
        jBGconsulta.add(jRBcpf);
        jRBcpf.setText("CPF");
        getContentPane().add(jRBcpf, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, -1, -1));

        jRBrg.setBackground(new java.awt.Color(255, 255, 255));
        jBGconsulta.add(jRBrg);
        jRBrg.setText("RG");
        getContentPane().add(jRBrg, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, 60, -1));

        jRBtodos.setBackground(new java.awt.Color(255, 255, 255));
        jBGconsulta.add(jRBtodos);
        jRBtodos.setSelected(true);
        jRBtodos.setText("Todos");
        getContentPane().add(jRBtodos, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 20, -1, -1));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setText("Selecione a linha desejada e clique em \"selecionar\".");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(155, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(324, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(22, 22, 22))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 410, 360));

        setSize(new java.awt.Dimension(408, 389));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jBselecionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBselecionarActionPerformed
        if (jTable1.getSelectedRow() > -1) {
            String nome = jTable1.getValueAt(jTable1.getSelectedRow(), 0).toString();
            Cliente cliente = ClienteDAO.obterPorNome(nome).get(0);
            cadastroDeClientes.consultaCliente(cliente);
            dispose();
        } else {
            JOptionPane.showMessageDialog(rootPane, "Favor selecionar uma linha");
        }
    }//GEN-LAST:event_jBselecionarActionPerformed

    private void jBprocurarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBprocurarActionPerformed
        if (jRBcpf.isSelected()) {
            List<Cliente> clientes = ClienteDAO.obterPorCpf(jTFbusca.getText());
            jTable1.setModel(new ClienteTableModel(clientes));
        }
        if (jRBrg.isSelected()) {
            List<Cliente> clientes = ClienteDAO.obterPorRG(jTFbusca.getText());
            jTable1.setModel(new ClienteTableModel(clientes));
        }
        if (jRBnome.isSelected()) {
            List<Cliente> clientes = ClienteDAO.obterPorNome(jTFbusca.getText());
            jTable1.setModel(new ClienteTableModel(clientes));
        }
        if (jRBtodos.isSelected()) {
            List<Cliente> clientes = ClienteDAO.obterTodos();
            jTable1.setModel(new ClienteTableModel(clientes));
        }
    }//GEN-LAST:event_jBprocurarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConsultaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConsultaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConsultaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConsultaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new ConsultaCliente().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup jBGconsulta;
    private javax.swing.JButton jBprocurar;
    private javax.swing.JButton jBselecionar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRBcpf;
    private javax.swing.JRadioButton jRBnome;
    private javax.swing.JRadioButton jRBrg;
    private javax.swing.JRadioButton jRBtodos;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTFbusca;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
