package mechanicalmanagement;

import dao.ClienteDAO;
import dao.MecanicoDAO;
import dao.OrdemServicoDAO;
import dao.VeiculoDAO;
import entidades.Cliente;
import entidades.OrdemServico;
import entidades.Veiculo;
import javax.swing.JOptionPane;
import tableModel.OrdemServicoTableModelo;

/**
 *
 * @author ctb03
 */
public class ConsultaOrdemServico extends javax.swing.JFrame {

    /**
     * Creates new form ConsultaOrdemServico
     */
    private CadastroDeOrdemServico cadastroDeOrdemServico;

    public ConsultaOrdemServico() {
        initComponents();
    }

    public ConsultaOrdemServico(CadastroDeOrdemServico cadastroDeOrdemServico) {
        this.cadastroDeOrdemServico = cadastroDeOrdemServico;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jBconsultar = new javax.swing.JButton();
        jTFconsulta = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jBselecionar = new javax.swing.JButton();
        jRBnomeCliente = new javax.swing.JRadioButton();
        jRBplacaVeiculo = new javax.swing.JRadioButton();
        jRBnomeMecanico = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jBconsultar.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jBconsultar.setText("Consultar");
        jBconsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBconsultarActionPerformed(evt);
            }
        });

        jTable1.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jTable1.setModel(new OrdemServicoTableModelo(OrdemServicoDAO.obterTodos()));
        jScrollPane1.setViewportView(jTable1);

        jBselecionar.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jBselecionar.setText("Selecionar");
        jBselecionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBselecionarActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRBnomeCliente);
        jRBnomeCliente.setText("Nome do Cliente");

        buttonGroup1.add(jRBplacaVeiculo);
        jRBplacaVeiculo.setText("Placa do Veiculo");

        buttonGroup1.add(jRBnomeMecanico);
        jRBnomeMecanico.setText("Nome do Mecânico");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jBselecionar))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 587, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jTFconsulta)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jBconsultar)))))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jRBnomeCliente)
                .addGap(18, 18, 18)
                .addComponent(jRBplacaVeiculo)
                .addGap(18, 18, 18)
                .addComponent(jRBnomeMecanico)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTFconsulta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBconsultar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRBnomeCliente)
                    .addComponent(jRBplacaVeiculo)
                    .addComponent(jRBnomeMecanico))
                .addGap(7, 7, 7)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBselecionar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBselecionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBselecionarActionPerformed
        if (jTable1.getSelectedRow() > -1) {
            String codigo = jTable1.getValueAt(jTable1.getSelectedRow(), 0).toString();
            cadastroDeOrdemServico.consultaOrdemServico(OrdemServicoDAO.obterPorCodigo(Integer.parseInt(codigo)).get(0));
            dispose();
        } else {
            JOptionPane.showMessageDialog(rootPane, "Favor selecionar uma linha");
        }
    }//GEN-LAST:event_jBselecionarActionPerformed

    private void jBconsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBconsultarActionPerformed
        if (jRBnomeCliente.isSelected()) {
            jTable1.setModel(new OrdemServicoTableModelo(OrdemServicoDAO.obterPorVeiculo(
                    VeiculoDAO.obterPorCliente(ClienteDAO.obterPorNome(jTFconsulta.getText()).isEmpty() ? null
                    : ClienteDAO.obterPorNome(jTFconsulta.getText()).get(0)).isEmpty() ? null
                    : VeiculoDAO.obterPorCliente(ClienteDAO.obterPorNome(jTFconsulta.getText()).isEmpty() ? null
                    : ClienteDAO.obterPorNome(jTFconsulta.getText()).get(0)).get(0))));
        }
        if (jRBnomeMecanico.isSelected()) {
            jTable1.setModel(new OrdemServicoTableModelo(OrdemServicoDAO.obterPorMecanico(
                    MecanicoDAO.obterPorNome(jTFconsulta.getText()).isEmpty()?null:
                    MecanicoDAO.obterPorNome(jTFconsulta.getText()).get(0))));
        }
        if (jRBplacaVeiculo.isSelected()) {
            jTable1.setModel(new OrdemServicoTableModelo(OrdemServicoDAO.obterPorVeiculo(
                    VeiculoDAO.obterPorPlaca(jTFconsulta.getText()).isEmpty()?null:
                    VeiculoDAO.obterPorPlaca(jTFconsulta.getText()).get(0))));
        }
    }//GEN-LAST:event_jBconsultarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConsultaOrdemServico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConsultaOrdemServico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConsultaOrdemServico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConsultaOrdemServico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new ConsultaOrdemServico().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jBconsultar;
    private javax.swing.JButton jBselecionar;
    private javax.swing.JRadioButton jRBnomeCliente;
    private javax.swing.JRadioButton jRBnomeMecanico;
    private javax.swing.JRadioButton jRBplacaVeiculo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTFconsulta;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
