package entidades;
// Generated 17/04/2013 10:28:10 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Cliente generated by hbm2java
 */
public class Cliente  implements java.io.Serializable {


     private Integer idCliente;
     private String nome;
     private String cpf;
     private String rg;
     private String telefone;
     private String endereco;
     private boolean status;
     private Set veiculos = new HashSet(0);

    public Cliente() {
    }

	
    public Cliente(String nome, String cpf, String rg, boolean status) {
        this.nome = nome;
        this.cpf = cpf;
        this.rg = rg;
        this.status = status;
    }

    public Cliente(String nome, String cpf, String rg, String telefone, String endereco, boolean status) {
        this.nome = nome;
        this.cpf = cpf;
        this.rg = rg;
        this.telefone = telefone;
        this.endereco = endereco;
        this.status = status;
    }
    
    public Cliente(String nome, String cpf, String rg, String telefone, String endereco, boolean status, Set veiculos) {
       this.nome = nome;
       this.cpf = cpf;
       this.rg = rg;
       this.telefone = telefone;
       this.endereco = endereco;
       this.status = status;
       this.veiculos = veiculos;
    }
   
    public Integer getIdCliente() {
        return this.idCliente;
    }
    
    public void setIdCliente(Integer idCliente) {
        this.idCliente = idCliente;
    }
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }
    public String getCpf() {
        return this.cpf;
    }
    
    public void setCpf(String cpf) {
        this.cpf = cpf;
    }
    public String getRg() {
        return this.rg;
    }
    
    public void setRg(String rg) {
        this.rg = rg;
    }
    public String getTelefone() {
        return this.telefone;
    }
    
    public void setTelefone(String telefone) {
        this.telefone = telefone;
    }
    public String getEndereco() {
        return this.endereco;
    }
    
    public void setEndereco(String endereco) {
        this.endereco = endereco;
    }
    public boolean isStatus() {
        return this.status;
    }
    
    public void setStatus(boolean status) {
        this.status = status;
    }
    public Set getVeiculos() {
        return this.veiculos;
    }
    
    public void setVeiculos(Set veiculos) {
        this.veiculos = veiculos;
    }




}


