package entidades;
// Generated 12/04/2013 13:39:36 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Cliente generated by hbm2java
 */
public class Cliente  implements java.io.Serializable {


     private Integer idCliente;
     private String nome;
     private int cpf;
     private int rg;
     private Integer telefone;
     private String endereco;
     private boolean status;
     private Set veiculos = new HashSet(0);

    public Cliente() {
    }

	
    public Cliente(String nome, int cpf, int rg, boolean status) {
        this.nome = nome;
        this.cpf = cpf;
        this.rg = rg;
        this.status = status;
    }
    public Cliente(String nome, int cpf, int rg, Integer telefone, String endereco, boolean status, Set veiculos) {
       this.nome = nome;
       this.cpf = cpf;
       this.rg = rg;
       this.telefone = telefone;
       this.endereco = endereco;
       this.status = status;
       this.veiculos = veiculos;
    }
   
    public Integer getIdCliente() {
        return this.idCliente;
    }
    
    public void setIdCliente(Integer idCliente) {
        this.idCliente = idCliente;
    }
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }
    public int getCpf() {
        return this.cpf;
    }
    
    public void setCpf(int cpf) {
        this.cpf = cpf;
    }
    public int getRg() {
        return this.rg;
    }
    
    public void setRg(int rg) {
        this.rg = rg;
    }
    public Integer getTelefone() {
        return this.telefone;
    }
    
    public void setTelefone(Integer telefone) {
        this.telefone = telefone;
    }
    public String getEndereco() {
        return this.endereco;
    }
    
    public void setEndereco(String endereco) {
        this.endereco = endereco;
    }
    public boolean isStatus() {
        return this.status;
    }
    
    public void setStatus(boolean status) {
        this.status = status;
    }
    public Set getVeiculos() {
        return this.veiculos;
    }
    
    public void setVeiculos(Set veiculos) {
        this.veiculos = veiculos;
    }




}


