package entidades;
// Generated 17/04/2013 10:28:10 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Mecanico generated by hbm2java
 */
public class Mecanico  implements java.io.Serializable {


     private Integer idMecanico;
     private String nome;
     private String rg;
     private String cpf;
     private String telefone;
     private String especialidade;
     private boolean status;
     private Set ordemServicos = new HashSet(0);

    public Mecanico() {
    }

	
    public Mecanico(String nome, String rg, String cpf, String especialidade, boolean status) {
        this.nome = nome;
        this.rg = rg;
        this.cpf = cpf;
        this.especialidade = especialidade;
        this.status = status;
    }

    public Mecanico(String nome, String rg, String cpf, String telefone, String especialidade, boolean status) {
        this.nome = nome;
        this.rg = rg;
        this.cpf = cpf;
        this.telefone = telefone;
        this.especialidade = especialidade;
        this.status = status;
    }
    
    public Mecanico(String nome, String rg, String cpf, String telefone, String especialidade, boolean status, Set ordemServicos) {
       this.nome = nome;
       this.rg = rg;
       this.cpf = cpf;
       this.telefone = telefone;
       this.especialidade = especialidade;
       this.status = status;
       this.ordemServicos = ordemServicos;
    }
   
    public Integer getIdMecanico() {
        return this.idMecanico;
    }
    
    public void setIdMecanico(Integer idMecanico) {
        this.idMecanico = idMecanico;
    }
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }
    public String getRg() {
        return this.rg;
    }
    
    public void setRg(String rg) {
        this.rg = rg;
    }
    public String getCpf() {
        return this.cpf;
    }
    
    public void setCpf(String cpf) {
        this.cpf = cpf;
    }
    public String getTelefone() {
        return this.telefone;
    }
    
    public void setTelefone(String telefone) {
        this.telefone = telefone;
    }
    public String getEspecialidade() {
        return this.especialidade;
    }
    
    public void setEspecialidade(String especialidade) {
        this.especialidade = especialidade;
    }
    public boolean isStatus() {
        return this.status;
    }
    
    public void setStatus(boolean status) {
        this.status = status;
    }
    public Set getOrdemServicos() {
        return this.ordemServicos;
    }
    
    public void setOrdemServicos(Set ordemServicos) {
        this.ordemServicos = ordemServicos;
    }




}


