package entidades;
// Generated 13/04/2013 16:02:52 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Mecanico generated by hbm2java
 */
public class Mecanico  implements java.io.Serializable {


     private Integer idMecanico;
     private String nome;
     private int cpf;
     private int rg;
     private String telefone;
     private String especialidade;
     private boolean status;
     private Set ordemServicos = new HashSet(0);
     private Set ordemServicos_1 = new HashSet(0);
     private Set ordemServicos_2 = new HashSet(0);

    public Mecanico() {
    }

	
    public Mecanico(String nome, int cpf, int rg, String especialidade, boolean status) {
        this.nome = nome;
        this.cpf = cpf;
        this.rg = rg;
        this.especialidade = especialidade;
        this.status = status;
    }

    public Mecanico(String nome, int cpf, int rg, String telefone, String especialidade, boolean status) {
        this.nome = nome;
        this.cpf = cpf;
        this.rg = rg;
        this.telefone = telefone;
        this.especialidade = especialidade;
        this.status = status;
    }
    
    public Mecanico(String nome, int cpf, int rg, String telefone, String especialidade, boolean status, Set ordemServicos, Set ordemServicos_1, Set ordemServicos_2) {
       this.nome = nome;
       this.cpf = cpf;
       this.rg = rg;
       this.telefone = telefone;
       this.especialidade = especialidade;
       this.status = status;
       this.ordemServicos = ordemServicos;
       this.ordemServicos_1 = ordemServicos_1;
       this.ordemServicos_2 = ordemServicos_2;
    }
   
    public Integer getIdMecanico() {
        return this.idMecanico;
    }
    
    public void setIdMecanico(Integer idMecanico) {
        this.idMecanico = idMecanico;
    }
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }
    public int getCpf() {
        return this.cpf;
    }
    
    public void setCpf(int cpf) {
        this.cpf = cpf;
    }
    public int getRg() {
        return this.rg;
    }
    
    public void setRg(int rg) {
        this.rg = rg;
    }
    public String getTelefone() {
        return this.telefone;
    }
    
    public void setTelefone(String telefone) {
        this.telefone = telefone;
    }
    public String getEspecialidade() {
        return this.especialidade;
    }
    
    public void setEspecialidade(String especialidade) {
        this.especialidade = especialidade;
    }
    public boolean isStatus() {
        return this.status;
    }
    
    public void setStatus(boolean status) {
        this.status = status;
    }
    public Set getOrdemServicos() {
        return this.ordemServicos;
    }
    
    public void setOrdemServicos(Set ordemServicos) {
        this.ordemServicos = ordemServicos;
    }
    public Set getOrdemServicos_1() {
        return this.ordemServicos_1;
    }
    
    public void setOrdemServicos_1(Set ordemServicos_1) {
        this.ordemServicos_1 = ordemServicos_1;
    }
    public Set getOrdemServicos_2() {
        return this.ordemServicos_2;
    }
    
    public void setOrdemServicos_2(Set ordemServicos_2) {
        this.ordemServicos_2 = ordemServicos_2;
    }




}


