package entidades;
// Generated 13/04/2013 16:02:52 by Hibernate Tools 3.2.1.GA



/**
 * PecaUsada generated by hbm2java
 */
public class PecaUsada  implements java.io.Serializable {


     private PecaUsadaId id;
     private OrdemServico ordemServico;
     private Peca peca;
     private double quantidade;

    public PecaUsada() {
    }

    public PecaUsada(PecaUsadaId id, OrdemServico ordemServico, Peca peca, double quantidade) {
       this.id = id;
       this.ordemServico = ordemServico;
       this.peca = peca;
       this.quantidade = quantidade;
    }
   
    public PecaUsadaId getId() {
        return this.id;
    }
    
    public void setId(PecaUsadaId id) {
        this.id = id;
    }
    public OrdemServico getOrdemServico() {
        return this.ordemServico;
    }
    
    public void setOrdemServico(OrdemServico ordemServico) {
        this.ordemServico = ordemServico;
    }
    public Peca getPeca() {
        return this.peca;
    }
    
    public void setPeca(Peca peca) {
        this.peca = peca;
    }
    public double getQuantidade() {
        return this.quantidade;
    }
    
    public void setQuantidade(double quantidade) {
        this.quantidade = quantidade;
    }




}


